version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3010:3010"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
